#config.yml for configuring server

port: 8080
host: "0.0.0.0"

central_image: "static/logo.svg"

instagram: "https://www.instagram.com/"
facebook: "https://www.facebook.com/"
youtube: "https://www.youtube.com/"

header: "pedaGoga is comming soon"
paragraph: "It's going to be useful! Subscribe to stay in touch with us. To get materials in form of the video instractions, user manuals and flayers."
